version: "3.7"
services:

  loginservice:
    container_name: login_server
    build: ./loginservice
    ports:
      - "5000:5000"
    volumes:
      - ./loginservice:/usr/share/app
    environment:
      SESSION_KEY: "AWODNOIndawldwad^*&(*)JIJ9021u31923u09wjdinwad"
      ENV: "development"
      PORT: ":5000"
      DB_URI: "postgres://root:root@dblogin:5432/loginS"
        # db_name://<username>:<password>:<service_name>:<port>/<db>
    depends_on:
      - dblogin
    restart: always

  dblogin:
    container_name: login_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: loginS
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./docker/loginService/init:/docker-entrypoint-initdb/initdb.sh
      - ./docker/loginService/pgdata:/var/lib/postgresql/data

  nginx:
    container_name: lreddit_nginx
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./lrui/build:/var/www/build
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - loginservice
      - dblogin
